kind: pipeline
name: default

steps:
- name: build-website
  image: angelfreak/docker-ssg:latest
  environment:
    SITE: tsrv.pw
    URL: https://tsrv.pw

- name: deploy-website
  image: drillster/drone-rsync
  settings:
    hosts:
      - '46.23.92.224'
    key:
      from_secret: plugin_key
    user:
      from_secret: plugin_user
    port: '2223'
    target: /home/www/tsrv.pw
    source: /dst
    recursive: true
    delete: true
