#Try 1
kind: pipeline
name: default

steps:
- name: build-website
  image: angelfreak/docker-ssg:latest
  environment:
    SITE: tsrv.pw
    URL: https://tsrv.pw

- name: deploy-website
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RYNC_USER:
      from_secret: rsync_user
  settings:
    hosts:
      from_secret: plugin_hosts
    port: "2223"
    source: ./dst/*
    target:
      from_secret: plugin_target
    recursive: true
    delete: true
