pipeline:
  build:
    image: angelfreak/docker-ssg
  branches: master

  deploy:
    image: drillster/drone-rsync
    hosts: [ "46.23.92.224:2222" ]
    user: angelfreak
    key:
      from_secret: plugin_key
    source: dst
    target: /var/www/tsrv.pw
    recursive: true
    delete: true
