#Try 1
kind: pipeline
name: default

steps:
- name: build-website
  image: angelfreak/docker-ssg:latest
  environment:
    SITE: tsrv.pw
    URL: https://tsrv.pw

- name: deploy-website
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: plugin_hosts
    user:
      from_secret: rsync_user
    key:
      from_secret: deploy_key
    port: 2223
    command_timeout: 2m
    target: /home/www/tsrv.pw/
    source:
      - ./dst/*
    strip_components: 1
