kind: pipeline
name: default

steps:
- name: build-website
  image: angelfreak/docker-ssg:latest
  environment:
    SITE: tsrv.pw
    URL: https://tsrv.pw

- name: deploy-website
  image: drillster/drone-rsync
  settings:
    port: "2223"
    source: ./dst/*
    recursive: true
    delete: true
    secrets: [ rsync_user, rsync_key, plugin_hosts, plugin_target ]
