#Try 1
kind: pipeline
name: default

steps:
- name: build-website
  image: angelfreak/docker-ssg:latest
  environment:
    SITE: tsrv.pw
    URL: https://tsrv.pw

- name: deploy-website
  image: drillster/drone-rsync
  hosts: [ "46.23.92.224" ]
  port: "2223"
  user: "angelfreak"
  secrets: [ rsync_key ]
  source: ./dst
  target: /var/www/tsrv.pw/
  recursive: true
  delete: true
