kind: pipeline
name: default

steps:
- name: build-website
  image: angelfreak/docker-ssg:latest
  environment:
    SITE: tsrv.pw
    URL: https://tsrv.pw

- name: deploy-website
  scp:
    image: appleboy/drone-scp
    settings:
      host: '46.23.92.224'
+     username: angelfreak
+     port: '2223'
      key:
        from_secret: plugin_key
      target: /home/www/tsrv.pw
      source: /dst
