#Try 1
kind: pipeline
name: default

steps:
- name: build-website
  image: angelfreak/docker-ssg:latest
  commands:
    - /bin/ssg5 ./src ./dst tsrv.pw https://tsrv.pw

- name: deploy-website
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: host
    user:
      from_secret: user
    key:
      from_secret: deploy_key
    port:
      from_secret: ssh_port
    command_timeout: 2m
    target: /home/www/tsrv.pw
    source:
      - ./dst/*
