baseurl = "https://tsrv.pw/"
languageCode = "en-dk"
title = "Freaksite"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]

#[params.logo]
#   path = "/img/your-example-logo.svg"
#   alt = ""
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "page/about"
